### ISSUE TITLE
Race condition on collection creation?

### ISSUE THREAD

**Issue by djMax** [scttnlsn/mubsub#32]
I have a CI test that essentially simulates an odd real-life use case where two mubsub instances may be connecting to a mongo instance at the same time. It's started 'reliably' throwing a "collection already exists" error. You can see the long stack trace here:

https://travis-ci.org/djMax/primus-mongodb

And the test that makes it happen:
https://github.com/djMax/primus-mongodb/blob/master/test/simple.js

**Comment by kof** [comment]
it must be trying to create the collection, just make sure it already exists ...
