### ISSUE TITLE
get ID

### ISSUE THREAD

**Issue by wormen** [scttnlsn/mubsub#44]
tell me what you need to set up, so that together with the data was ID

**Comment by scttnlsn** [comment]
Sorry, I don't understand.  Could you elaborate a bit more on what you're trying to figure out?

**Comment by wormen** [comment]
I subscribe to the events come only transmitted data
How can I get an ID specific event?

**Comment by scttnlsn** [comment]
You'll need to listen for all messages and check the IDs:

```js
```

**Comment by scttnlsn** [comment]
Don't think there's a way to do this right now.

**Comment by scttnlsn** [comment]
You could listen to all messages and check for some condition on the message:

```js
channel.on('message', function (message) {
  if (isTheMessageIWant(message)) {
    // do something
  }
});
```

**Comment by wormen** [comment]
I need ID, without any conditions

**Comment by scttnlsn** [comment]
Not possible with the current implementation

**Comment by wormen** [comment]
when the opportunity arises?

**Comment by scttnlsn** [comment]
Not sure what you're asking

**Comment by omakoleg** [comment]
If You mean mongo collection document `_id` then just subscribe to `document ` event. There is complete mongo document available.
Didnt run it, but should be like this:
```javascript
channel.on('document', function (document) {
// document._id should be set
}
```
