### ISSUE TITLE
Just Want to Use it to Subscribe,How?

### ISSUE THREAD

**Issue by yuz11** [scttnlsn/mubsub#47]
Here is the case. I've got a capped collection,with data flowing in.I want to use mubsub to subscribe it(like the codes below)

var mongoClient = mubsub('mongodb://localhost:27017/escache');
function run() {
    var cacheChannel = mongoClient.channel('cache');
    mongoClient.on('error', console.error);
    cacheChannel.on('error', console.error);
    cacheChannel.subscribe([],function (message) {
        msgCnt += 1;
        console.log(message);
        if(msgCnt % 10000 == 0){
            console.log("recv Msg:",msgCnt);
        }
    });
    cacheChannel.on('message',function(message){
        console.log(message);
    })
}

But no message in.
mongostat info like below
insert query update delete getmore command % dirty % used flushes vsize  res qr|qw ar|aw netIn netOut conn     time
  8500    *0     *0     *0       0     1|0     1.4    7.1       0  4.8G 4.5G   0|0   1|0   11m    16k  143 16:32:46
 11278    *0     *0     *0       0     1|0     1.4    6.9       0  4.8G 4.5G   0|0   1|1   15m    16k  143 16:32:47
  9092    *0     *0     *0       0    18|0     1.6    7.1       0  4.8G 4.5G   0|1   1|0   12m    19k  143 16:32:48
  8630    *0     *0     *0       0     1|0     1.8    7.3       0  4.8G 4.5G   0|0   1|0   13m    16k  143 16:32:49
 11000     2     *0     *0       0     5|0     2.2    7.7       0  4.8G 4.5G   0|0   2|0   16m    19k  148 16:32:50
 10301    *0     *0     *0       0     1|0     1.3   14.3       0  4.8G 4.5G   0|0   2|2   14m    16k  148 16:32:51
  7699    *0     *0     *0       0     1|0     1.3   23.7       0  4.8G 4.5G   0|0   2|0   11m    16k  148 16:32:52
  7500    *0     *0     *0       0     1|0     1.3   33.6       0  4.8G 4.5G   0|0   2|0    9m    16k  148 16:32:53
 10545    *0     *0     *0       0     1|0     1.7   43.7       0  4.8G 4.5G   0|0   2|1   15m    16k  148 16:32:54
 12137    *0     *0     *0       0     2|0     1.3   52.3       0  4.8G 4.5G   0|0   2|1   16m    17k  148 16:32:55

Must I use pub method to insert data to mongo?or I can format data in some pattern so that I can get it out with mubsub.

thx in adwance

**Comment by scttnlsn** [comment]
You do not need to use the Mubsub client in order to publish messages.  Insert documents with the following form:

```js
{
  "event": "<event name>",
  "message": {
    ...
  }
}
```

**Comment by yuz11** [comment]
Thank u. I read your source code then change a little bit to meet my demand as I already get a form for my data. It's working now. Really appreciate for what u have done.

**Comment by scttnlsn** [comment]
Great!  Glad it's working for you.
