### ISSUE TITLE
node-mongodb-native later than 2.1.7 causes high CPU usage

### ISSUE THREAD

**Issue by Faleij** [scttnlsn/mubsub#49]
MongoDB 3.2.1
Node 4.2.2
npm 2.14.7

Reproduce:
1. make a new folder
2. copy example mubsub implementation from readme to app.js
3. npm install mubsub
4. node app

**Comment by lklepner** [comment]
+1

**Comment by lklepner** [comment]
I'm guessing the issue is the change to mongo-core in 1.3.3 mentioned in the history as "Fixed issue where tailable cursor would not retry even though cursor was still alive."

https://github.com/christkv/mongodb-core/blob/V1.3.4/HISTORY.md
